const ActionTypes = {
    LOADER: 'LOADER',
    COURSESUBJECT: "COURSESUBJECT",
    CURRENTUSER: 'CURRENTUSER',
    SELECTEDSUBJECTCOURSES: "SELECTEDSUBJECTCOURSES",
    COURSEDATALOADER: "COURSEDATALOADER",
}

export default ActionTypes;
