export const countries = [
    `Accounting`,
    `Business Communications`,
    `Business Economics & Public Policy`,
    `Business Law`,
    `Finance`,
    `Management & Organizations`,
    `Marketing`,
    `Strategy`,
    `Technology & Operations`,
    `Business Networks`,
    `Entrepreneurship`,
    `Global Business`,
    `Healthcare`,
    `Leadership`,
    `Positive Business`,
    `Real Estate`,
    `Social Impact`,
    `Supply Chain Management`,
    `Sustainability`,
    `Tax Policy`,
];
export const year= [  
    `2023`,
    `2024`,
    `2025`,
];
